baseURL = 'https://pboyd.io/'
languageCode = 'en-us'
title = 'pboyd.io'
theme = 'std'
enableRobotsTXT = true

[markup]
  [markup.highlight]
    style = 'github-dark'

[menus]
    [[menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
    [[menus.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 20
    [[menus.main]]
        name = 'About'
        pageRef = '/about'
        weight = 30
    [[menus.main]]
        weight = 40
        name = 'RSS'
        pre = '<img src="/rss-icon.png" alt="RSS"></img>'
        url = '/index.xml'
